### ISSUE TITLE
is error?

### ISSUE THREAD

**Issue by gyhyoyo** [miguelsolorio/gulp-auto-imagemin#2]
events.js:141
      throw er; // Unhandled 'error' event
      ^

use cnpm install is ok, use npm install error  . why? please tell me ,thanks

**Comment by miguelsolorio** [comment]
Can you provide me with the full error? Also, what OS and node version are you running?

**Comment by gyhyoyo** [comment]
I am using Windows 7 system. Problem has been solved, thank you！
